name: buildGKI
on:
  workflow_dispatch:
    inputs:
      patch:
        description: 'Patch kernel (Droidspace requires)'
        type: boolean
        default: true
      patch_file:
        description: 'Patch file path'
        type: choice
        default: '001.GKI-below-6.12-fix_sysvipc_kabi_3_4_5.patch'
        options:
          - '001.GKI-below-6.12-fix_sysvipc_kabi_1_2_3.patch'
          - '001.GKI-below-6.12-fix_sysvipc_kabi_3_4_5.patch'
          - '001.GKI-below-6.12-fix_sysvipc_kabi_6_7_8.patch'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils \
          default-jdk git gnupg flex bison gperf build-essential zip curl libc6-dev libncurses-dev libx11-dev libreadline-dev libgl1 libgl1-mesa-dev \
          python3 make sudo gcc g++ bc grep tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev python-is-python3 libc6-dev libtinfo6 \
          make repo cpio kmod openssl libelf-dev pahole libssl-dev libarchive-tools zstd rsync --fix-missing && wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb
      
      - name: Configure git identity
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install repo tool
        run: |
            sudo curl -sS https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
            sudo chmod a+x /usr/local/bin/repo

      - name: Sync kernel sources with repo
        run: |
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android14-6.1-2025-06 --depth=1
          repo sync -c --no-tags --no-clone-bundle -j$(nproc)

      - name: Setup fragment
        if: ${{ inputs.patch == true }}
        working-directory: ${{ github.workspace }}/common
        run: |
          cp ${{ github.workspace }}/droidspace_requires.fragment arch/arm64/configs/

      - name: Apply patch for Droidspace
        if: ${{ inputs.patch == true }}
        working-directory: ${{ github.workspace }}/common
        run: |
          patch -p1 -F 5 --ignore-whitespace < ${{ github.workspace }}/${{ inputs.patch_file }}
          git commit -am "Applied patch for Droidspace"

      - name: Build GKI kernel
        run: |
          if [ "${{ inputs.patch }}" == "true" ]; then
            tools/bazel run //common:kernel_aarch64_dist --lto=thin --defconfig_fragment=//common:arch/arm64/configs/droidspace_requires.fragment -- --dist_dir=out/dist
          else
            tools/bazel run //common:kernel_aarch64_dist --lto=thin -- --dist_dir=out/dist
          fi

      - name: Display Info
        run: |
          printf "GKI kernel build completed. Displaying artifact information:"
          uname -a
          ls -lh out/dist/
          ls -lh build/kernel/kleaf/bazelrc/
          du -sh out/dist/

      - name: Upload GKI kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Image
          path: |
            out/dist/Image
      - name: Upload GKI kernel modules
        uses: actions/upload-artifact@v4
        with:
          name: modules
          path: out/dist/*.ko

      - name: Upload Debug Symbols
        uses: actions/upload-artifact@v4
        with:
          name: vmlinux
          path: out/dist/vmlinux